### PR TITLE
css two column layout

### PR DESCRIPTION
**Pull request by Han-Zhang-fuze**
Screenshot 2022-05-13 232101

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Han! Your line spacing on the subheader in the first row and the text in the second row is incorrect as compared to the example. Please revise and submit a new screenshot with your revision.

**Comment by Han-Zhang-fuze** [comment]
Screenshot 2022-05-15 114020

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Han! Please rename your classes to follow proper layout classes name scheming. Also, make sure you do not pollute your layout classes with additional styling, you should make new classes for any additional styling necessary. As a rule:
- `container` classes should have a `max-width` and `margin-left` and `margin-right` set to `auto`
- `row` classes should have `display: flex` and nothing else
- `column` classes should have `flex-basis` or `width` and nothing else

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
